apiVersion: umo.nofacepeace.github.io/v1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: middleware-sample
spec:
  # TODO(user): Add fields here
