# This rule is not used by the project umo-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to umo.localhost resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: umo-controller
    app.kubernetes.io/managed-by: kustomize
  name: umocluster-viewer-role
rules:
- apiGroups:
  - umo.localhost
  resources:
  - umoclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - umo.localhost
  resources:
  - umoclusters/status
  verbs:
  - get
