apiVersion: umo.localhost/v1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/name: umo
    app.kubernetes.io/managed-by: kustomize
  name: middleware-sample
spec:
  # TODO(user): Add fields here
